
trainers:
  # use this trainer name unless you want KD or other custom thing
  default_trainer:
    optimizer:
      class: SGD    
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001

    lr_scheduler:
      class: ExponentialLR
      gamma: 0.9
      epochs: [20, 20, 100]

